### ISSUE TITLE
Low resolution on new chromecast HD (v4)

### ISSUE THREAD

**Issue by pparent76** [stestagg/dashcast#22]
The cast resolution with Dashcast is lower than 720p, on the new chromecast by google (white).

**Comment by pparent76** [comment]
I had this line on my webpage
<meta name="viewport" content="width=device-width, initial-scale=1">

Removing it solved the problem.

**Comment by ljak** [comment]
> I had this line on my webpage

What do you meant ? 
Like, you had a specific HTML tag triggering the issue ?
