### ISSUE TITLE
DashCast not working

### ISSUE THREAD

**Issue by ValeriZamulin** [stestagg/dashcast#9]
Hi, something is happened with dashcast after Chrome update, it is not working any more!

**Comment by TempestDash** [comment]
Chrome 73 will no longer cast websites that are not HTTPS and the current host for DashCast is on plain old HTTP. There is a workaround, but it may leave you vulnerable to other things:

> go to chrome://flags/#unsafely-treat-insecure-origin-as-secure
> enable unsafely-treat-insecure-origin-as-secure
> add http://stestagg.github.io/dashcast/

You'll have to restart Chrome for it to take effect.  Some have commented that Chrome periodically forgets this setting, so put this down in a Keep or something so you can refer back to it.

EDIT: There is an exception to this behavior for localhost, you could also solve this problem by downloading DashCast and running it on a device on your own network.  An existing server or a Raspberry Pi or something...

**Comment by royalexpressions** [comment]
how do you download dashcast?

**Comment by ValeriZamulin** [comment]
> Chrome 73 will no longer cast websites that are not HTTPS and the current host for DashCast is on plain old HTTP. There is a workaround, but it may leave you vulnerable to other things:
> 
> > go to chrome://flags/#unsafely-treat-insecure-origin-as-secure
> > enable unsafely-treat-insecure-origin-as-secure
> > add http://stestagg.github.io/dashcast/
> 
> You'll have to restart Chrome for it to take effect. Some have commented that Chrome periodically forgets this setting, so put this down in a Keep or something so you can refer back to it.
> 
> EDIT: There is an exception to this behavior for localhost, you could also solve this problem by downloading DashCast and running it on a device on your own network. An existing server or a Raspberry Pi or something...

Super! I Run Dashcast on my own network and it's working well! Thank You for help!

**Comment by ValeriZamulin** [comment]
> how do you download dashcast?

Hi! You can do it from here
![image](https://user-images.githubusercontent.com/39791233/55776215-a58b0a80-5aa4-11e9-9e97-8875d0af5896.png)
